export const states = [
    { id: 'acre', value: 'Acre', label: 'Acre' },
    { id: 'alagoas', value: 'Alagoas', label: 'Alagoas' },
    { id: 'amapa', value: 'Amapá', label: 'Amapá' },
    { id: 'amazonas', value: 'Amazonas', label: 'Amazonas' },
    { id: 'bahia', value: 'Bahia', label: 'Bahia' },
    { id: 'ceara', value: 'Ceará', label: 'Ceará' },
    {
        id: 'distrito_federal',
        value: 'Distrito Federal',
        label: 'Distrito Federal',
    },
    { id: 'espirito_santo', value: 'Espírito Santo', label: 'Espírito Santo' },
    { id: 'goias', value: 'Goiás', label: 'Goiás' },
    { id: 'maranhao', value: 'Maranhão', label: 'Maranhão' },
    { id: 'mato_grosso', value: 'Mato Grosso', label: 'Mato Grosso' },
    {
        id: 'mato_grosso_do_sul',
        value: 'Mato Grosso do Sul',
        label: 'Mato Grosso do Sul',
    },
    { id: 'minas_gerais', value: 'Minas Gerais', label: 'Minas Gerais' },
    { id: 'para', value: 'Pará', label: 'Pará' },
    { id: 'paraiba', value: 'Paraíba', label: 'Paraíba' },
    { id: 'parana', value: 'Paraná', label: 'Paraná' },
    { id: 'pernambuco', value: 'Pernambuco', label: 'Pernambuco' },
    { id: 'piaui', value: 'Piauí', label: 'Piauí' },
    { id: 'rio_de_janeiro', value: 'Rio de Janeiro', label: 'Rio de Janeiro' },
    {
        id: 'rio_grande_do_norte',
        value: 'Rio Grande do Norte',
        label: 'Rio Grande do Norte',
    },
    {
        id: 'rio_grande_do_sul',
        value: 'Rio Grande do Sul',
        label: 'Rio Grande do Sul',
    },
    { id: 'rondonia', value: 'Rondônia', label: 'Rondônia' },
    { id: 'roraima', value: 'Roraima', label: 'Roraima' },
    { id: 'santa_catarina', value: 'Santa Catarina', label: 'Santa Catarina' },
    { id: 'sao_paulo', value: 'São Paulo', label: 'São Paulo' },
    { id: 'sergipe', value: 'Sergipe', label: 'Sergipe' },
    { id: 'tocantins', value: 'Tocantins', label: 'Tocantins' },
];
