export const states = [
    { id: 'Acre', value: 'Acre', label: 'Acre' },
    { id: 'Alagoas', value: 'Alagoas', label: 'Alagoas' },
    { id: 'Amapa', value: 'Amapá', label: 'Amapá' },
    { id: 'Amazonas', value: 'Amazonas', label: 'Amazonas' },
    { id: 'Bahia', value: 'Bahia', label: 'Bahia' },
    { id: 'Ceara', value: 'Ceará', label: 'Ceará' },
    {
        id: 'Distrito Federal',
        value: 'Distrito Federal',
        label: 'Distrito Federal',
    },
    { id: 'Espirito Santo', value: 'Espírito Santo', label: 'Espírito Santo' },
    { id: 'Goias', value: 'Goiás', label: 'Goiás' },
    { id: 'Maranhao', value: 'Maranhão', label: 'Maranhão' },
    { id: 'Mato Grosso', value: 'Mato Grosso', label: 'Mato Grosso' },
    {
        id: 'Mato Grosso do Sul',
        value: 'Mato Grosso do Sul',
        label: 'Mato Grosso do Sul',
    },
    { id: 'Minas Gerais', value: 'Minas Gerais', label: 'Minas Gerais' },
    { id: 'Para', value: 'Pará', label: 'Pará' },
    { id: 'Paraiba', value: 'Paraíba', label: 'Paraíba' },
    { id: 'Parana', value: 'Paraná', label: 'Paraná' },
    { id: 'Pernambuco', value: 'Pernambuco', label: 'Pernambuco' },
    { id: 'Piaui', value: 'Piauí', label: 'Piauí' },
    { id: 'Rio de Janeiro', value: 'Rio de Janeiro', label: 'Rio de Janeiro' },
    {
        id: 'Rio Grande do Norte',
        value: 'Rio Grande do Norte',
        label: 'Rio Grande do Norte',
    },
    {
        id: 'Rio Grande do Sul',
        value: 'Rio Grande do Sul',
        label: 'Rio Grande do Sul',
    },
    { id: 'Rondonia', value: 'Rondônia', label: 'Rondônia' },
    { id: 'Roraima', value: 'Roraima', label: 'Roraima' },
    { id: 'Santa Catarina', value: 'Santa Catarina', label: 'Santa Catarina' },
    { id: 'Sao Paulo', value: 'São Paulo', label: 'São Paulo' },
    { id: 'Sergipe', value: 'Sergipe', label: 'Sergipe' },
    { id: 'Tocantins', value: 'Tocantins', label: 'Tocantins' },
];
